---
apiVersion: v1
kind: Service
metadata:
  name: pictshare
  labels:
    app: pictshare
spec: 
  ports:
  - port: 80
    protocol: TCP
  type: NodePort
  selector:
    app: pictshare

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pictshare-data
  labels:
    app: pictshare
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pictshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pictshare
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pictshare
    spec:
      containers:
      - name: pictshare
        image: tritran14/pictshare:<VERSION>
        ports:
          - containerPort: 80
            name: http-port
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        volumeMounts:
            - mountPath: /var/www/data
              name: pictshare-volume
      volumes:
        - name: pictshare-volume
          persistentVolumeClaim:
            claimName: pictshare-data
      restartPolicy: Always

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: pictshare-hpa
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    #apiVersion: extensions/v1
    apiVersion: apps/v1
    kind: Deployment
    name: pictshare
  targetCPUUtilizationPercentage: 90
